she_codes_news/news/urls.py
from django.urls import path
from . import views
from .views import SearchView


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    # path('search/<str:username>/', SearchView.as_view(), name='search'),
    path('search/', SearchView.as_view(), name='search')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
   ]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, ViewProfileView

app_name ='users'

urlpatterns = [    
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/profile', ViewProfileView.as_view(), name='profile'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model

USER = get_user_model()


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="stories"
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image = models.URLField(null=True, blank=True)

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    profile_image = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    pass

    def _str_(self):
        return self.username
    

    

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        #Below controls user input. 
        fields = ['title', 'pub_date', 'image', 'content']
        widgets = {
            'pub_date': forms.DateTimeInput(
                format= '%m/%d/%Y %H:%M',
                attrs= {
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'datetime-local'
                }
            )
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser



class CustomUserCreationForm (UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'bio', 'profile_image']

she_codes_news/news/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.views import generic, View
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import CustomUser
from django.shortcuts import render






class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        return context
    
class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(LoginRequiredMixin, generic.CreateView):
    login_url = 'login'
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    

class SearchView(View):
    template_name = 'news/search.html'

    def get(self, request, *args, **kwargs):
        query = request.GET.get('q', '')
        news_results = NewsStory.objects.filter(author__username__icontains=query)

        context = {
            'news_results': news_results,
            'query': query,
        }

        return render(request, self.template_name, context)


    

she_codes_news/users/views.py
from typing import Any
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm
from news.models import NewsStory


class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

    
class ViewProfileView(generic.DetailView):
    model = CustomUser
    template_name = 'users/profile.html'
    context_object_name = 'author'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['user_stories'] = NewsStory.objects.filter(author=self.kwargs['pk']).order_by('-pub_date')

        return context
    

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}



{% block content %}
<div>
        <form id="story-form" action="" method="post">
            {% csrf_token %}
            {{ form.as_p }} 
            <input type="submit" value="submit">
        </form>
</div>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}




{% block content %}
<br>
<a href="{% url 'news:newStory' %}">Write New Story</a>


    <h2>Latest News</h2>

        <div id="latest-stories">
            {% if latest_stories %}
                {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
                {% endfor %}
            {% else %}
                <p>No stories are available.</p>
            {% endif %}
        </div>

        <div id="all-stories">
            {% if latest_stories %}
                {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
                {% endfor %}
            {% else %}
                <p>No stories are available.</p>
            {% endif %}
        </div>
{% endblock %}

she_codes_news/news/templates/news/search.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}">
{% endblock %}

{% block content %}

{% if news_results %}
        <ul>
        {% for news in news_results %}
            <li>{{ news.title }} {{ news.content }} by {{ news.author.username }}</li>
        {% endfor %}
{% else %}
    <p>I may need to find a new muse...check back later to check out my creative genius!</p>
{% endif %}

{% endblock %}

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}

{% block content%}
<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        {% if story.image %}
            <img src="{{ story.image }}"/>
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image %}
            <img src="{{ story.image }}"/>
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>

    </a>
</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Cathy O Halloran">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She Codes News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
{% block content %}

{% endblock %}

<footer>
    <p>@CathyOH 2023</p>
        <a href="https://www.linkedin.com/in/cathy-o-halloran-60687b288/">
            <img class="link_logo"   src="static/images/linkedin.jpg"> 
        </a>
        <a href="https://github.com/COHally">
            <img class="link_logo"   src="static/images/GitHub_logo.png">
        </a>
</footer>
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a href="profile">{{ user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
    {% if request.user.is_authenticated %}
    
    {%else%}
    <a href="{% url 'users:createAccount' %}">Create Account</a>
    {%endif%}

    <form action="{% url 'news:search' %}" method="get">
        <input type="text" name="q" placeholder="Search news...">
        <button type="submit">Search</button>
    </form>
</nav>

she_codes_news/users/templates/users/createAccount.html
<!-- users/templates/users/createAccount.html -->

{% extends 'base.html' %}

{% block content %}
    <h2>Create Account</h2>
    <form method="post">    
        {% csrf_token %}        
        {{ form.as_p }}
        <button type="submit">Create Account</button>
    </form>

    <a href="{% url 'login' %}"> Already have an account? Great, login here. </a>
{% endblock %}

she_codes_news/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}">
{% endblock %}

{% block content %}
<div class="auth-details"></div>
<h2>Hello {{ user.username }}</h2>
<div class="auth-details-wrapper">
    {% if user.profile_image != None %}
    <img class="prof_image" src="{ url 'users\images\avatar.jpg' }">
    {% endif %}
    <div>
            <p><span class="bio-heading">Name:</span> {{ author.username }}</p>
            <p><span class="bio-heading">Email:</span> <a href="mailto:{{author.email}}">{{ user.email }}</a></p>
            <p class="bio-heading">Bio: {{ author.bio }}</p>

        {% if author.stories %}
            <h3>Written by me....</h3>
            {% for story in author.stories.all %}
            {% include 'news/storycard.html' %}
            {% empty %}
                <p>I may need to find a new muse...check back later to check out my creative genius!</p>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}